---
title: "FAIR Check Analysis"
author: "Matt Jones"
date: "1/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(arrow)
library(here)
devtools::load_all()
```

```{r}
run_results <- open_dataset(here("../metadig-data/run-data-0.5.0")) %>% 
    collect() %>% 
    rename(pid = obj_id, obsoletedBy = obsoleted_by)
data_clean <- assign_sequence_id(run_results) # takes about 5 minutes

runs <- data_clean %>% 
    mutate(dialect = case_when(
        grepl("ecoinformatics", format_id) ~ "EML",
        grepl("isotc211", format_id) ~ "ISO",
        grepl("schema", format_id) ~ "SOSO"
    )) %>% 
    rename(dateUploaded = date_uploaded)

runs_ver <- get_first_last_versions(runs)

check_results <- open_dataset(here("../metadig-data/check-data-0.5.0"))
```

# Summarize check data

NB: This is currently for just a subset of nodes!

```{r summary}
checks_calc <- check_results %>% 
    inner_join(runs_ver) %>% 
    mutate(
        check_status = if_else(grepl("error", tolower(check_output)), "ERROR", check_status),
    ) %>%
    filter(check_status != "ERROR") %>% 
    group_by(check_name, dialect, check_type, check_level) %>%
    summarise(
        total_runs = n(),
        mean_score = mean(check_status == "SUCCESS", na.rm = TRUE) * 100,
        .groups = "drop"
    ) %>%
    collect()


plot_ready <- checks_calc %>%
  mutate(check_name_sorted = tidytext::reorder_within(check_name, mean_score, check_type))

ggplot(plot_ready, aes(x = mean_score, y = check_name_sorted)) +
  geom_point(aes(color = dialect), size = 3, alpha = 0.8) +
  facet_wrap(~ check_type, scales = "free_y", ncol = 2) +
  tidytext::scale_y_reordered() +
  scale_color_manual(
      values = c(
          "EML" = "#26547c", 
          "ISO" = "#ef476f", 
          "SOSO" = "#ffd166"
      )
  ) +
  theme_bw() +
  theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = "gray95"),
      strip.text = element_text(face = "bold", size = 11)
  ) +
    labs(x = "", y = "")
```




Figure-03_2020-09-30_CalculatedChangeOfIndividualDocs.jpg
Figure-12_2020-11-05_AggregateScores-FAIR-RunningMean.png


