---
title: "FAIR Check Analysis"
author: "Matt Jones"
date: "1/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, echo=FALSE}
library(tidyverse)
```

```{r load_check_data, eval=FALSE, echo=FALSE}
load_check_data <- function() {
  check_data <- "check-data"
  run_files <- list.files(path = check_data, pattern = "fair-2.1-runs-.*\\.csv$")
  check_files <- list.files(path = check_data, pattern = "fair-2.1-checks-.*\\.csv$")

  run_col_types <- cols(
    X1="-",
    run_id="c",
    obj_id="c",
    series_id="c",
    suite_id="c",
    run_status="c",
    origin_mn="c",
    date_uplaoded="c",
    format_id="c",
    obsoletes="c",
    filename="c"
  )
  runs <- paste0(check_data, "/", run_files) %>%
    map_df(read_csv, col_names = TRUE, col_types = run_col_types)

  checks_joined <- paste0(check_data, "/", check_files) %>%
    map_df(read_csv, col_names = TRUE) %>%
    select(-X1) %>%
    left_join(runs, by = "run_id")
}

checks_joined <- load_check_data()
```

# Summarize check data

NB: This is currently for just a subset of nodes!

```{r summary}
checks_subset <- checks_joined %>% 
  filter(origin_mn %in% c("urn:node:ARCTIC", "urn:node:KNB", "urn:node:ESS_DIVE"))

overall_status <- checks_subset %>% 
  group_by(origin_mn, check_level) %>% 
  summarize(n=n())

ggplot(checks_subset, aes(x=check_level, fill=check_status)) + 
  geom_bar(position="fill") +
  theme_bw() +
  facet_wrap(facets = origin_mn ~ check_type, ncol = 4)

#checks_current <- checks_subset %>% 
#  filter
```


# Mark each document with its version chain

- p2 obsoletes p1
- p3 obsoletes p2

pid | obsoletes | obsoleted_by
----|-----------|-------------
p1  | NA        | p2
p2  | p1        | p3
p3  | p2        | NA

```{r}
set_obsoleted_by <- function(df, pid_target) {
  row <- filter(df, pid==pid_target)
  pids <- c(pid_target)
  obsoletes_pid <- row$obsoletes
  
  # walk the obsoletes tree backwards and set the obsoleted_by field
  while (!is.na(obsoletes_pid)) {
    print(paste0("Processing pid: ", pid_target))

    # Add the pid to the list of pids
    pids <- c(obsoletes_pid, pids)

    # Record the obsoleted_by relation
    df <- df %>% 
      mutate(obsoleted_by = ifelse(pid==obsoletes_pid, pid_target, obsoleted_by))
    
    # Get the row for the pid that obsoletes the doc
    row <- filter(df, pid==obsoletes_pid)
    pid_target <- obsoletes_pid
    obsoletes_pid <- row$obsoletes
  }
  
  # Set the serial version for the returned pids
  # This depends on the pids being in order from oldest to newest
  cur_version <- 1
  for (p in pids) {
    df <- df %>% 
      mutate(ser_version = ifelse(pid==p, cur_version, ser_version))
    cur_version <- cur_version + 1
  }
  
  return(df)
}

df <- data.frame(pid = c("p1", "p2", "p3"),
                 obsoletes = c(NA, "p1", "p2"),
                 obsoleted_by = c(NA, NA, NA), 
                 stringsAsFactors = FALSE)
df
for (pid in df$pid) {
  df <- set_obsoleted_by(df, pid)
}
df
```


```{r}
get_all_versions <- function(runs, pid) {
  stopifnot(is.character(pid),
            nchar(pid) > 0)

  pids <- c(pid)

  # Walk backward
  sm <- getSystemMetadata(node, pid)

  while (!is.na(sm@obsoletes)) {
    oldsm <- sm # Save a copy for better warning messages
    sm <- getSystemMetadata(node, sm@obsoletes)

    if (is.null(sm)) {
      warning(call. = FALSE,
              paste0("An incomplete version chain has been returned. ", oldsm@identifier, " obsoletes ", oldsm@obsoletes, " but ", oldsm@obsoletes, " could not be found. This can be due to the object not existing or not having correct permission to view it."))
      break
    }

    pids <- c(sm@identifier, pids)
  }

  # Then forward from the start pid
  sm <- getSystemMetadata(node, pid)

  while (!is.na(sm@obsoletedBy)) {
    oldsm <- sm # Save a copy for better warning messages
    sm <- getSystemMetadata(node, sm@obsoletedBy)

    if (is.null(sm)) {
      warning(call. = FALSE,
              paste0("An incomplete version chain has been returned. ", oldsm@identifier, " is obsoleted by ", oldsm@obsoletedBy, " but ", oldsm@obsoletedBy, " could not be found. This can be due to the object not existing or not having correct permission to view it."))
      break
    }

    pids <- c(pids, sm@identifier)
  }

  pids
}
```

