---
title: "Quantifying FAIR"
author: "Matt Jones"
date: "5/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(tidyverse)
library(lubridate)
library(DT)
```

```{r load_data}
fsr <- read_csv("../data/FAIR-scores-ranked.csv")
scores <- mutate(fsr, ym = as.Date(sprintf("%4s-%02d-01", year(dateUploaded), month(dateUploaded)))) %>%
      mutate(scoreF = scoreFindable * 100.0) %>%
      mutate(scoreA = scoreAccessible * 100.0) %>%
      mutate(scoreI = scoreInteroperable * 100.0) %>%
      mutate(scoreR = scoreReusable * 100.0) %>%
      mutate(dialect = case_when(grepl("eml", formatId) ~ "EML", grepl("iso", formatId) ~ "ISO"))

most_recent <- scores %>%
  arrange(ym, seriesId, version) %>%
  group_by(ym, seriesId) %>%
  top_n(1, version)
head(most_recent)
```

```{r count_standards}
standards <- data.frame(table(most_recent$dialect)) %>%
  rename(dialect=Var1, n=Freq)
```

## Overall FAIR asssessment

Combined across all repositories and across metadata dialects.

```{r calc_cumulative_overall}
score_cumulative <- most_recent %>%
  arrange(ym) %>%
  group_by(ym) %>%
  summarise(f=mean(scoreF), a=mean(scoreA), i=mean(scoreI), r=mean(scoreR)) %>%
  mutate(fc=cummean(f), ac=cummean(a), ic=cummean(i), rc=cummean(r)) %>%
  select(ym, f, a, i, r, fc, ac, ic, rc) %>%
  gather(metric, mean, -ym)
score_cumulative$metric <- factor(score_cumulative$metric,
                                  levels=c("f", "a", "i", "r", "fc", "ac", "ic", "rc"),
                                  labels=c("Findable", "Accessible", "Interoperable", "Reusable",
                                           "Cum. Findable", "Cum. Accessible", "Cum. Interoperable", "Cum. Reusable"))
score_monthly <- score_cumulative %>% filter(metric %in% c("Findable", "Accessible", "Interoperable", "Reusable"))
score_cumulative_alone <- score_cumulative %>% filter(metric %in% c("Cum. Findable", "Cum. Accessible", "Cum. Interoperable", "Cum. Reusable"))
```

```{r plot_cumulative_overall}
d1_colors <- c("#ff582d", "#c70a61", "#1a6379", "#60c5e4", "#ff582d", "#c70a61", "#1a6379", "#60c5e4")
p <- ggplot(data=score_cumulative_alone, mapping=aes(x=ym, y=mean, color=metric)) +
  geom_line() +
  geom_point(size=1) +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  scale_colour_manual(values=d1_colors) +
  scale_x_date(date_breaks="year", date_minor_breaks="months", labels=date_format("%Y")) +
  xlab("Year") +
  scale_y_continuous(limits=c(0,100)) +
  ylab("Average FAIR Score") +
  ggtitle(paste0("DataONE: FAIR scores for ", format(sum(standards$n), big.mark=","), " EML and ISO metadata records"))
ggsave("../images/dataone-fair-scores-overall.png", width = 8, height = 4)
p
```

And also examine the monthly variance.

```{r plot_monthly_overall}
p <- ggplot(data=score_monthly, mapping=aes(x=ym, y=mean, color=metric)) +
  geom_line() +
  geom_point(size=1) +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  scale_colour_manual(values=d1_colors) +
  scale_x_date(date_breaks="year", date_minor_breaks="months", labels=date_format("%Y")) +
  xlab("Year") +
  scale_y_continuous(limits=c(0,100)) +
  ylab("Average FAIR Score") +
  ggtitle(paste0("DataONE: FAIR scores for ", format(sum(standards$n), big.mark=","), " EML and ISO metadata records"))
ggsave("../images/dataone-fair-scores-overall-monthly.png", width = 8, height = 4)
p
```

## Assessment of EML and ISO metadata corpora

Combined across all repositories, but split across metadata dialects.

```{r calc_cumulative_by_dialect}
score_dialect <- most_recent %>%
  group_by(dialect, ym) %>%
  summarise(f=mean(scoreF), a=mean(scoreA), i=mean(scoreI), r=mean(scoreR)) %>%
  mutate(fc=cummean(f), ac=cummean(a), ic=cummean(i), rc=cummean(r)) %>%
  select(dialect, ym, f, a, i, r, fc, ac, ic, rc) %>%
  gather(metric, mean, -dialect, -ym)
score_dialect$metric <- factor(score_dialect$metric,
                                  levels=c("f", "a", "i", "r", "fc", "ac", "ic", "rc"),
                                  labels=c("Findable", "Accessible", "Interoperable", "Reusable",
                                           "Cum. Findable", "Cum. Accessible", "Cum. Interoperable", "Cum. Reusable"))

```

```{r plot_cumulative_by_dialect}
cum_dialect <- score_dialect %>% filter(metric %in% c("Cum. Findable", "Cum. Accessible", "Cum. Interoperable", "Cum. Reusable"))

p <- ggplot(data=cum_dialect, mapping=aes(x=ym, y=mean, color=metric)) +
  geom_line() +
  geom_point(size=1) +
  facet_grid(dialect ~ .) +
  theme_bw() +
  theme(panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  scale_colour_manual(values=d1_colors) +
  scale_x_date(date_breaks="year", date_minor_breaks="months", labels=date_format("%Y")) +
  xlab("Year") +
  scale_y_continuous(limits=c(0,100)) +
  ylab("Average FAIR Score") +
  ggtitle(paste0("DataONE: FAIR scores for ", format(standards$n[standards$dialect == "EML"], big.mark=","), " EML and ", format(standards$n[standards$dialect == "ISO"], big.mark=","), " ISO metadata records"))
ggsave("../images/dataone-fair-scores-dialect.png", width = 8, height = 4)
p
```

