---
title: "FAIR Scores: Initial Analysis of Aggregate FAIR Scores"
author: "Christopher Beltz"
date: "10/7/2020"
output: html_document
abtract: R packages updated on 2020-10-12. Rmd updated on 2020-10-12.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup Environment


Load libraries:

```{r}
library(tidyverse)
library(reshape2)
library(patchwork)
library(here)
```


Load, clean, subset, and calculated change on individual check data:

```{r}
#Load and clean individual check data
source(here("code", "Aggregate-Scores", "01_Cleaning_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR scores over time
source(here("code", "Aggregate-Scores", "02_Calculation_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())
```


\pagebreak



#Data Visualization

```{r}
#quick histogram of scores (Note: not sure what is up with the negative scores)
ggplot(aggChecks_clean_withCalcs, aes(x=overallDIFF)) +
  geom_histogram(color="black", fill="white")
```


##Figure 6a:

```{r}
#subset data for initial only
agg_INITIAL <- aggChecks_clean_withCalcs %>%
  filter(dateSplit=="INITIAL")

#over time
plot.overall <- ggplot(agg_INITIAL[agg_INITIAL$dateSplit=="INITIAL",], aes(x=dateUploaded, y=overallDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  ylab("Change in Overall FAIR Score") +
  xlab("Date of Initial Dataset Submission") +
  theme_minimal()

plot.F <- ggplot(agg_INITIAL[agg_INITIAL$dateSplit=="INITIAL",], aes(x=dateUploaded, y=findableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.A <- ggplot(agg_INITIAL[agg_INITIAL$dateSplit=="INITIAL",], aes(x=dateUploaded, y=accessibleDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.I <- ggplot(agg_INITIAL[agg_INITIAL$dateSplit=="INITIAL",], aes(x=dateUploaded, y=interoperableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.R <- ggplot(agg_INITIAL[agg_INITIAL$dateSplit=="INITIAL",], aes(x=dateUploaded, y=reusableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())
```

####Create final combined image using `patchwork`
#NOTE: https://patchwork.data-imaginist.com/articles/guides/layout.html
```{r}
FAIR_layout <- "
  AAAAAA
  AAAAAA
  BBBCCC
  BBBCCC
  DDDEEE
  DDDEEE
"
```


```{r}
#create final plot
plot6a <- plot.overall + plot.F + plot.A + plot.I + plot.R +
  plot_layout(design = FAIR_layout) +
  plot_annotation(title = 'Change in FAIR scores from initial submission to final upload',
                  caption = '2020-10-09',
                  subtitle = '2010 - present')

plot6a
```


```{r, eval=FALSE}
#save plot as PNG to aurora
ggsave(filename="Figure-06a_2020-10-09_AggregateScores-FAIR-ChangeOverTime-SubmissionDate.png",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```


```{r}
rm(list=setdiff(ls(), c("checks_aggregate_ADC", "aggChecks_clean_withCalcs", "agg_INITIAL", "plot6a")))
```


##Figure 6b:

```{r}
#subset data for initial only
agg_FINAL <- aggChecks_clean_withCalcs %>%
  filter(dateSplit=="FINAL")

#over time
plot.overall <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL",], aes(x=dateUploaded, y=overallDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  ylab("Change in Overall FAIR Score") +
  xlab("Date of Final Dataset Publication") +
  theme_minimal()

plot.F <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL",], aes(x=dateUploaded, y=findableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.A <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL",], aes(x=dateUploaded, y=accessibleDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.I <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL",], aes(x=dateUploaded, y=interoperableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.R <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL",], aes(x=dateUploaded, y=reusableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())
```

####Create final combined image using `patchwork`
#NOTE: https://patchwork.data-imaginist.com/articles/guides/layout.html
```{r}
FAIR_layout <- "
  AAAAAA
  AAAAAA
  BBBCCC
  BBBCCC
  DDDEEE
  DDDEEE
"
```


```{r}
#create final plot
plot6b <- plot.overall + plot.F + plot.A + plot.I + plot.R +
  plot_layout(design = FAIR_layout) +
  plot_annotation(title = 'Change in FAIR scores from initial submission to final upload',
                  caption = '2020-10-09',
                  subtitle = '2010 - present')

plot6b
```


```{r, eval=FALSE}
#save plot as PNG to aurora
ggsave(filename="Figure-06b_2020-10-09_AggregateScores-FAIR-ChangeOverTime-PublicationDate.jpg",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```


```{r}
rm(list=setdiff(ls(), c("checks_aggregate_ADC", "aggChecks_clean_withCalcs", "agg_INITIAL", "agg_FINAL", "plot6a", "plot6b")))
```


##Figure 6c:

```{r}
#over time
plot.overall <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL" & agg_FINAL$dateUploaded>as.POSIXct("2016-03-21 00:00:01"),], aes(x=dateUploaded, y=overallDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  ylab("Change in Overall FAIR Score") +
  xlab("Date of Final Dataset Publication") +
  theme_minimal()

plot.F <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL" & agg_FINAL$dateUploaded>as.POSIXct("2016-03-21 00:00:01"),], aes(x=dateUploaded, y=findableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.A <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL" & agg_FINAL$dateUploaded>as.POSIXct("2016-03-21 00:00:01"),], aes(x=dateUploaded, y=accessibleDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.I <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL" & agg_FINAL$dateUploaded>as.POSIXct("2016-03-21 00:00:01"),], aes(x=dateUploaded, y=interoperableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1) +
  theme_minimal() +
  theme(axis.title.x = element_blank())

plot.R <- ggplot(agg_FINAL[agg_FINAL$dateSplit=="FINAL" & agg_FINAL$dateUploaded>as.POSIXct("2016-03-21 00:00:01"),], aes(x=dateUploaded, y=reusableDIFF)) +
  geom_point(alpha=0.5, fill="#B5E1E7", color="1D254E", pch=21, size=1.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank())
```

####Create final combined image using `patchwork`
#NOTE: https://patchwork.data-imaginist.com/articles/guides/layout.html
```{r}
FAIR_layout <- "
  AAAAAA
  AAAAAA
  BBBCCC
  BBBCCC
  DDDEEE
  DDDEEE
"
```


```{r}
#create final plot
plot6c <- plot.overall + plot.F + plot.A + plot.I + plot.R +
  plot_layout(design = FAIR_layout) +
  plot_annotation(title = 'Change in FAIR scores from initial submission to final upload',
                  caption = '2020-10-09',
                  subtitle = '2016-03-21 to present')

plot6c
```


```{r, eval=FALSE}
#save plot as PNG to aurora
ggsave(filename="Figure-06c_2020-10-09_AggregateScores-FAIR-ChangeOverTime-PublicationDate-post2016.jpg",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```


```{r}
rm(list=setdiff(ls(), c("checks_aggregate_ADC", "aggChecks_clean_withCalcs", "agg_INITIAL", "agg_FINAL", "plot6a", "plot6b", "plot6c")))
```









