---
title: "FAIR Scores: Aggregate FAIR Scores Analysis using Google Analytics and NSF figure"
author: "Christopher Beltz"
date: "10/12/2020"
output: html_document
abtract: R packages updated on 2020-10-12. Rmd updated on 2020-10-12.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup Environment


Load libraries:

```{r}
library(tidyverse)
library(reshape2)
library(patchwork)
library(here)
```


Load, clean, subset, and calculated change on individual check data:

```{r}
#Load and clean individual check data
source(here("code", "Aggregate-Scores", "01_Cleaning_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR scores over time
source(here("code", "Aggregate-Scores", "02_Calculation_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())
```


\pagebreak



#Data Exploration

```{r}
preADC_seqId <- aggChecks_clean_withCalcs %>%
  group_by(sequenceId) %>%
  filter(dateSplit=="INITIAL",
         dateUploaded < parse_datetime("2016-03-21")) %>%
  summarise(n=n())

aggChecks_pre2016 <- aggChecks_clean_withCalcs[which((aggChecks_clean_withCalcs$sequenceId %in% preADC_seqId$sequenceId)),]

aggChecks_post2016 <- aggChecks_clean_withCalcs[which(!(aggChecks_clean_withCalcs$sequenceId %in% preADC_seqId$sequenceId)),]
```



#Data Visualization

#Figure 7a:

```{r}
#summarize the RAW initial and final scores
plotData_7 <- aggChecks_post2016 %>%
    group_by(dateSplit) %>% 
  summarise(OVERALL = mean(scoreOverall),
            Findable = mean(scoreFindable),
            Accessible = mean(scoreAccessible),
            Interoperable = mean(scoreInteroperable),
            Reusable = mean(scoreReusable)) %>%
  pivot_longer(cols=c(OVERALL, Findable, Accessible, Interoperable, Reusable),
               names_to = "scoreType",
               values_to = "meanScore")

#change dateSplit variable names to re-order in legend
plotData_7$dateSplit <- ifelse(plotData_7$dateSplit=="INITIAL", "2INITIAL", "3FINAL")

#change levels for better plotting
plotData_7$dateSplit <- factor(plotData_7$dateSplit, levels = c("1preADC", "2INITIAL", "3FINAL"))
plotData_7$scoreType <- factor(plotData_7$scoreType, levels = c("Reusable", "Interoperable", "Accessible", "Findable", "OVERALL"))
```

```{r}
#create graphical parameters
colorValues <- c("2INITIAL" = "gray60", "3FINAL" = "orangered1")
fillValues <- c("1preADC" = "yellow", "2INITIAL" = "gray80", "3FINAL" = "black")
shapeValues <- c("1preADC" = 23, "2INITIAL" = 21, "3FINAL" = 21)
sizeValues <- c("1preADC" = 2, "2INITIAL" = 2, "3FINAL" = 2)
```

```{r}
plot7a <- ggplot(plotData_7, aes(x=meanScore, y=scoreType)) +
  geom_line(aes(group=scoreType, color=dateSplit), size=1.2) +
  geom_point(aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  scale_shape_manual(values=shapeValues,
                     name="FAIR Score at",
                     labels=c("initial submission", "final publication")) +
  scale_fill_manual(values=fillValues,
                    name="FAIR Score at",
                    labels=c("initial submission", "final publication")) +
  scale_color_manual(values=colorValues,
                     name="FAIR Score is",
                     labels=c("improving", "deteriorating")) +
  scale_size_manual(values=sizeValues) +
  xlim(0,1) +
  theme_minimal() +
  xlab("Mean FAIR Score") +
  ylab("")
```

```{r}
plot7a <- plot7a + plot_annotation(
  title = 'Proportion of metadata meeting aggregate FAIR Scores',
  subtitle = 'for the Arctic Data Center (2016-03-21 to present)',
  caption = '2020-10-13'
)
```

```{r}
plot7a
```


```{r, eval=FALSE}
#save plot as JPG to Aurora
ggsave(filename="Figure-07a_2020-10-13_AggregateScores-FAIR-Simple.jpg",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```



#Figure 7b:

```{r}
#summarize the RAW initial and final scores for pre-2016 data
plotData_7_pre2016 <- aggChecks_pre2016 %>%
    group_by(dateSplit) %>% 
  summarise(OVERALL = mean(scoreOverall),
            Findable = mean(scoreFindable),
            Accessible = mean(scoreAccessible),
            Interoperable = mean(scoreInteroperable),
            Reusable = mean(scoreReusable)) %>%
  pivot_longer(cols=c(OVERALL, Findable, Accessible, Interoperable, Reusable),
               names_to = "scoreType",
               values_to = "meanScore") %>%
  filter(dateSplit=="FINAL") %>%
  mutate(dateSplit="1preADC")

#change levels for better plotting
plotData_7_pre2016$scoreType <- factor(plotData_7_pre2016$scoreType, levels = c("Reusable", "Interoperable", "Accessible", "Findable", "OVERALL"))
```


```{r}
plot7b <- ggplot(plotData_7, aes(x=meanScore, y=scoreType)) +
  geom_line(aes(group=scoreType, color=dateSplit), size=1.2) +
  geom_point(aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  geom_point(data = plotData_7_pre2016, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  scale_shape_manual(values=shapeValues,
                     name="FAIR Score for",
                     labels=c( "pre-ADC data", "initial submission", "final publication")) +
  scale_fill_manual(values=fillValues,
                    name="FAIR Score for",
                    labels=c( "pre-ADC data", "initial submission", "final publication")) +
  scale_color_manual(values=colorValues,
                     name="FAIR Score is",
                     labels=c("improving", "deteriorating")) +
  scale_size_manual(values=sizeValues) +
  xlim(0,1) +
  theme_minimal() +
  xlab("Mean Score") +
  ylab("FAIR Category") +
    theme(legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  guides(size = FALSE, 
         fill = guide_legend(override.aes = list(size = 3)))
```

```{r}
plot7b <- plot7b + plot_annotation(
  title = 'Proportion of metadata meeting aggregate FAIR Scores',
  subtitle = 'for the Arctic Data Center (2016-03-21 to present) and pre-ADC data',
  caption = '2020-10-15'
)
```

```{r}
plot7b
```


```{r, eval=FALSE}
#save plot as JPG to Aurora
ggsave(filename="Figure-07b_2020-10-15_AggregateScores-FAIR-Simple.jpg",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```



```{r}
rm(list=setdiff(ls(), c("checks_aggregate_ADC", "aggChecks_clean_withCalcs", "plotData_7", "plot7a")))
```
