---
title: "FAIR Scores: Aggregate FAIR Scores Analysis using `gganimate` for NSF Figure"
author: "Christopher Beltz"
date: "10/21/2020"
output: html_document
abtract: R packages updated on 2020-10-21. Rmd updated on 2020-10-21.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup Environment


Load libraries:

```{r}
library(tidyverse)
library(reshape2)
library(gganimate)
library(patchwork)
library(here)
```


Load ADC theme for ggplot
```{r}
devtools::source_url("https://raw.github.nceas.ucsb.edu/KNB/arctic-data/master/reporting/R/theme_ADC.R?token=AAAABNRLO3IMGU55A4PESF27UGP2K")
```


Load, clean, subset, and calculated change on individual check data:

```{r}
#Load and clean individual check data
source(here("code", "Aggregate-Scores", "01_Cleaning_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR scores over time
source(here("code", "Aggregate-Scores", "02_Calculation_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())
```


\pagebreak



#Data Exploration


```{r}
gganimate_NSF_weekly <- checks_aggregate_ADC %>%
  filter(dateUploaded > as.Date("2016-03-20")) %>%
  mutate(year = lubridate::year(dateUploaded),
         month = lubridate::month(dateUploaded),
         week = lubridate::week(dateUploaded),
         date_floor = lubridate::floor_date(dateUploaded, "1 week")) %>%
  group_by(year, month, week, date_floor) %>%
  summarize(n=n(),
            meanOverall = mean(scoreOverall),
            meanFindable = mean(scoreFindable),
            meanAccessible = mean(scoreAccessible),
            meanInteroperable = mean(scoreInteroperable),
            meanReusable = mean(scoreReusable))

gganimate_NSF_monthly <- checks_aggregate_ADC %>%
    filter(dateUploaded > as.Date("2016-03-20")) %>%
  mutate(year = lubridate::year(dateUploaded),
         month = lubridate::month(dateUploaded),
         week = lubridate::week(dateUploaded),
         date_floor = lubridate::floor_date(dateUploaded, "1 month")) %>%
  group_by(year, month, date_floor) %>%
  summarize(n=n(),
            meanOverall = mean(scoreOverall),
            meanFindable = mean(scoreFindable),
            meanAccessible = mean(scoreAccessible),
            meanInteroperable = mean(scoreInteroperable),
            meanReusable = mean(scoreReusable))
```


```{r}
plot10 <- ggplot() +
  annotate('rect', xmin = as.POSIXct("2016-03-22"), xmax = as.POSIXct("2016-12-31"), ymin = -Inf, ymax = -0.1, fill='#084594', alpha=0.3) +
    annotate('rect', xmin = as.POSIXct('2016-12-31'), xmax = as.POSIXct('2017-09-15'), ymin = -Inf, ymax = -0.1, fill='#2171B5', alpha=0.3) +
  annotate('rect', xmin = as.POSIXct('2017-09-15'), xmax = as.POSIXct('2018-06-15'), ymin = -Inf, ymax = -0.1, fill='#4292C6', alpha=0.3) +
  annotate('rect', xmin = as.POSIXct('2018-06-15'), xmax = as.POSIXct('2019-03-15'), ymin = -Inf, ymax = -0.1, fill="#6BAED6", alpha=0.3) +
  annotate('rect', xmin = as.POSIXct('2019-03-15'), xmax = as.POSIXct('2020-01-01'), ymin = -Inf, ymax = -0.1, fill="grey55", alpha=0.3) +
  annotate('rect', xmin = as.POSIXct('2020-01-01'), xmax = as.POSIXct('2020-10-15'), ymin = -Inf, ymax = -0.1, fill="#6BAED6", alpha=0.3) +
  annotate('text', x = as.POSIXct('2016-08-21'), y = -150, label = "ADC Opens", fontface='bold.italic', size = 3) +
  annotate('text', x = as.POSIXct('2017-05-25'), y = -150, label = "special thing\n #1", fontface = 'bold.italic', size = 3) +
  annotate('text', x = as.POSIXct('2018-02-18'), y = -150, label = "special thing\n #2", fontface = 'bold.italic', size = 3) +
  annotate('text', x = as.POSIXct('2018-10-31'), y = -150, label = "special thing\n #3", fontface = 'bold.italic', size = 3) +
  annotate('text', x = as.POSIXct('2019-08-15'), y = -150, label = "FAIR 0.2.1", fontface = 'bold.italic', size = 3) +
  annotate('text', x = as.POSIXct('2020-05-25'), y = -150, label = "FAIR 0.3.2", fontface = 'bold.italic', size = 3) +
  annotate("curve", x = as.POSIXct("2016-09-15"), xend = as.POSIXct("2016-03-30"), y = 3250, yend = 2750, curvature = 0.5, 
           size = .75, arrow = arrow(length = unit(2, "mm")), colour = "firebrick") +
  annotate('text', x = as.POSIXct('2017-04-15'), y = 3250, label = "ACADIS data imported", fontface = 'bold.italic', size = 3) +
  geom_bar(data = gganimate_NSF_weekly, aes(x=date_floor, y=n, group=seq_along(date_floor)), stat = 'identity', alpha=0.5) +
  geom_line(data = gganimate_NSF_monthly, aes(x=date_floor, y=meanOverall*3000), color = "black", size = 0.95, linetype="solid", alpha=1.0) +
  geom_line(data = gganimate_NSF_monthly, aes(x=date_floor, y=meanFindable*3000), color = "blue", size = 0.5, linetype="dashed", alpha=0.45) +
  geom_line(data = gganimate_NSF_monthly, aes(x=date_floor, y=meanAccessible*3000), color = "green", size = 0.5, linetype="dashed", alpha=0.45) +
  geom_line(data = gganimate_NSF_monthly, aes(x=date_floor, y=meanInteroperable*3000), color = "orange", size = 0.5, linetype="dashed", alpha=0.45) +
  geom_line(data = gganimate_NSF_monthly, aes(x=date_floor, y=meanReusable*3000), color = "red", size = 0.5, linetype="dashed", alpha=0.45) +
  scale_y_continuous(name = 'Weekly Dataset Uploads', 
                     sec.axis = sec_axis(~./3000, name = "Mean Monthly FAIR Score")) +
  labs(x = "Date") +
  scale_x_datetime(date_breaks = "1 year", date_labels="%Y") +
  theme_ADC

plot10
```


```{r, eval=FALSE}
#save plot as JPG to Aurora
ggsave(filename="Figure-09_2020-10-27_AggregateScores-FAIR-gganimate-static.jpg",
       path=here("figures"),
       bg="transparent",
       dpi = 300,
       units="in",
       width=9.5,
       height=6)
```


```{r}
plot10_animate <- plot10 +
  transition_reveal(date_floor) +
  view_follow()
```


```{r}
#create GIF
gif_plot10_small <-animate(plot10_animate, nframes=25)

gif_plot10_small
```


```{r, eval=FALSE}
#create high resolution `gganimate` plot
gif_plot10 <- animate(plot10_animate, height=5, width=10, units='in', res=300, fps=10, end_pause = 10) #this takes ~2 minutes

gif_plot10
```


```{r, EVAL=FALSE}
#save GIF
anim_save(here("figures", "Figure-10_2020-10-22_gganimate-FAIR-Scores.gif"), gif_plot10)
```






