---
title: 'FAIR Scores: Initial Analysis of Google Analytics view data'
author: "Christopher Beltz"
date: "9/21/2020"
output: html_document
abtract: R packages updated on 2020-10-13. Rmd updated on 2020-10-13.
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#Setup Environment


Load libraries:

```{r}
library(tidyverse)
library(reshape2)
library(patchwork)
library(here)
```


Load, clean, and subset Google analytics data:

```{r, eval=TRUE}
#Load and clean individual check data
source(here("code", "Google-Analytics_views", "01_Cleaning_Google-Analytics-Views.R"), local = knitr::knit_global())

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR checks over time, and calculated length of curation time (i.e., submission length).
source(here("code", "Google-Analytics_views", "02_Calculation_Google-Analytics-Views.R"), local = knitr::knit_global())
```


Load, clean, subset, and calculte change in aggregate FAIR scores:

```{r, eval=TRUE}
#Load and clean aggregate check data
source(here("code", "Aggregate-Scores", "01_Cleaning_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR scores over time
source(here("code", "Aggregate-Scores", "02_Calculation_Aggregate-FAIR-Scores.R"), local = knitr::knit_global())
```

```{r}
#remove unneeded raw data
rm(checks_aggregate_ADC, GA_analytics_views)
```



\pagebreak



#Data Exploration

```{r}
#summarize views for each DOI
GA_summary <- GA_views_clean %>%
  group_by(Page) %>%
  summarise(totalViews=sum(Pageviews),
            totalUniqueViews=sum(`Unique Pageviews`))
```

```{r}
aggChecks_summary <- aggChecks_clean_withCalcs %>%
  filter(dateSplit=="FINAL") %>%
  mutate(containsDOI=str_detect(pid, "doi:")) %>%
  filter(containsDOI=="TRUE")
```

```{r}
agg_GA_joined <- left_join(aggChecks_summary, GA_summary, by=c("pid"="Page"))

agg_GA_joined <- agg_GA_joined[!is.na(agg_GA_joined$totalViews),]
```


#Data Visualization

###Figure 8a:


```{r}
ggplot(agg_GA_joined, aes(x=scoreOverall, y=totalUniqueViews)) + 
  geom_point() +
  geom_smooth(method="gam")
```


###Figure 8b:


```{r}
ggplot(agg_GA_joined[agg_GA_joined$scoreOverall>0.55,], aes(x=scoreOverall, y=totalUniqueViews)) + 
  geom_point() +
  geom_smooth(method="gam")
```


###Figure 8c:


```{r}
ggplot(agg_GA_joined, aes(x=scoreOverall, y=totalUniqueViews)) + 
  geom_point() +
  geom_smooth(method="gam") +
  facet_wrap(~year)

```


###Figure 8d:

```{r}
#remove everything with less than 5 views
agg_GA_joined_overFive <- agg_GA_joined[agg_GA_joined$totalViews>=5,]
```


```{r}
ggplot(agg_GA_joined_overFive, aes(x=scoreOverall, y=totalUniqueViews)) + 
  geom_point() +
  geom_smooth(method="gam") +
  facet_wrap(~year)
```


###Figure 8d:

```{r}
#remove everything with less than 10 views
agg_GA_joined_overTen <- agg_GA_joined[agg_GA_joined$totalUniqueViews>=10 & agg_GA_joined$year>2016,]
```


```{r}
ggplot(agg_GA_joined_overTen, aes(x=scoreOverall, y=totalUniqueViews)) + 
  geom_point() +
  geom_smooth(method="gam")
```

