---
title: "FAIR Scores: Investigating Curation Practices"
author: "Christopher Beltz"
date: "10/1/2020"
output: html_document
abtract: R packages updated on 2020-10-08. Rmd updated on 2020-10-08.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup Environment


Load libraries:

```{r}
library(tidyverse)
library(reshape2)
library(patchwork)
library(here)
library(dataone)
library(arcticdatautils)
library(EML)
```


Load, clean, subset, and calculated change on individual check data:

```{r, eval=FALSE}
#THIS TAKES ~11 MINUTES TO RUN ON AURORA. FOR CONVENIENCE USE THE ARCHIVED DATA IN THE NEXT CODE CHUCK STARTING ON LINE 42.
#Load and clean individual check data
source(here("code", "01a_Cleaning_Individual-FAIR-Checks_CWBeltz.R"), local = knitr::knit_global()) #This takes ~30 seconds on Aurora.

#Subset cleaned data to include only original first/last versions (i.e., metadata submission and final publication), calculate change in FAIR checks over time, and calculated length of curation time (i.e., submission length).
source(here("code", "02a_Calculation_Individual-FAIR-Checks_CWBeltz.R"), local = knitr::knit_global()) #This takes ~10 minutes on Aurora
```


```{r}
#load cleaned data from 2020-09-30 created using the code chunk above
checks_individual_ADC <- readRDS(here("data", "scores_checks", "cleaned", "checks_individual_ADC_2020-09-30.rds"))
indivChecks_clean_withCalcs <- readRDS(here("data", "scores_checks", "cleaned", "indivChecks_clean_2020-09-30.rds"))
remove_series_id <- readRDS(here("data", "scores_checks", "cleaned", "remove_series_id_2020-09-30.rds"))
```



\pagebreak


#Subset Data

```{r}
preADC_series_id <- indivChecks_clean_withCalcs %>%
  group_by(series_id) %>%
  filter(dateSplit=="INITIAL",
         date_uploaded < parse_datetime("2016-03-21")) %>%
  summarise(n=n())

indivChecks_pre2016 <- indivChecks_clean_withCalcs[which((indivChecks_clean_withCalcs$series_id %in% preADC_series_id$series_id)),]

indivChecks_post2016 <- indivChecks_clean_withCalcs[which(!(indivChecks_clean_withCalcs$series_id %in% preADC_series_id$series_id)),]
```



#Data Visualizations

###Figure 5:


```{r}
plotData_5_pre <- indivChecks_pre2016 %>%
  group_by(check_type, check_level, check_name, dateSplit) %>%
  summarise(n=n(), 
            mean=mean(check_status_num)) %>%
  filter(dateSplit=="FINAL") %>%
  mutate(dateSplit = gsub("FINAL", "ACADIS", dateSplit))



plotData_5_post2016 <- indivChecks_post2016 %>%
  group_by(check_type, check_level, check_name, dateSplit) %>%
  summarise(n=n(), 
            mean=mean(check_status_num))

plotData_5_2020 <- indivChecks_post2016 %>%
  filter(dateSplit=="FINAL", year == "2020") %>%
  group_by(check_type, check_level, check_name, dateSplit) %>%
  summarise(n=n(), 
            mean=mean(check_status_num)) %>%
    mutate(dateSplit = gsub("FINAL", "2020", dateSplit))


```

```{r}
#create graphical parameters
colorValues <- c("INITIAL" = "gray60", "FINAL" = "orangered1")
fillValues <- c("INITIAL" = "gray80", "FINAL" = "black", "ACADIS" = "yellow", "2020" = "#19B36A")
shapeValues <- c("INITIAL" = 21, "FINAL" = 21, "ACADIS" = 24, "2020" = 23)
sizeValues <- c("INITIAL" = 2, "FINAL" = 2, "ACADIS" = 3, "2020" = 3)
```

```{r}
plot5a <- ggplot(plotData_5_post2016, aes(x=mean, y=check_name %>% forcats::fct_reorder(-mean))) +
  geom_point(data=plotData_5_post2016, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  geom_line(data=plotData_5_post2016, aes(group=check_name, color=dateSplit), size=1.2) +
  geom_point(data=plotData_5_post2016, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  facet_wrap(~ check_type, scale="free") +
  scale_shape_manual(values=shapeValues,
                     name="FAIR Score at",
                     labels=c("final publication (ADC-wide)", "initial submission (ADC-wide)")) +
  scale_fill_manual(values=fillValues,
                    name="FAIR Score at",
                    labels=c("final publication (ADC-wide)", "initial submission (ADC-wide)")) +
  scale_color_manual(values=colorValues,
                     name="FAIR Score is",
                     labels=c("improving", "deteriorating")) +
  scale_size_manual(values=sizeValues) +
  theme_minimal() +
  xlab("") +
  ylab("") +
  theme(strip.text.x = element_text(size = 14, colour = "black", face="bold"),
        panel.border = element_rect(colour = "black", fill=NA)) +
  theme(legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  guides(size = FALSE, 
         fill = guide_legend(override.aes = list(size = 4)))
```

```{r}
plot5a <- plot5a + plot_annotation(
  title = 'Proportion of metadata meeting individual FAIR checks',
  subtitle = 'for the Arctic Data Center and ACADIS',
  caption = '2020-10-08'
)
```

```{r}
plot5a
```


```{r, eval=FALSE}
#save plot as PNG to aurora
ggsave(filename="Figure-05a_2020-10-08_FAIR-IndividualChecksOverTime_post2016.jpg",
       path=here("figures"),
       dpi = 400,
       units="in",
       width=13,
       height=7.3)
```


```{r}
plot5b <- ggplot(plotData_5_post2016, aes(x=mean, y=check_name %>% forcats::fct_reorder(-mean))) +
  geom_point(data=plotData_5_post2016, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  geom_line(data=plotData_5_post2016, aes(group=check_name, color=dateSplit), size=1.2) +
  geom_point(data=plotData_5_pre, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  geom_point(data=plotData_5_post2016, aes(fill=dateSplit, shape=dateSplit, size=dateSplit)) +
  facet_wrap(~ check_type, scale="free") +
  scale_shape_manual(values=shapeValues,
                     name="FAIR Score at",
                     labels=c("ACADIS", "final publication (ADC-wide)", "initial submission (ADC-wide)")) +
  scale_fill_manual(values=fillValues,
                    name="FAIR Score at",
                    labels=c("ACADIS", "final publication (ADC-wide)", "initial submission (ADC-wide)")) +
  scale_color_manual(values=colorValues,
                     name="FAIR Score is",
                     labels=c("improving", "deteriorating")) +
  scale_size_manual(values=sizeValues) +
  theme_minimal() +
  xlab("") +
  ylab("") +
  theme(strip.text.x = element_text(size = 14, colour = "black", face="bold"),
        panel.border = element_rect(colour = "black", fill=NA)) +
  theme(legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  guides(size = FALSE, 
         fill = guide_legend(override.aes = list(size = 4)))
```

```{r}
plot5b <- plot5b + plot_annotation(
  title = 'Proportion of metadata meeting individual FAIR checks',
  subtitle = 'for the Arctic Data Center and ACADIS',
  caption = '2020-10-08'
)
```

```{r}
plot5b
```


```{r, eval=FALSE}
#save plot as PNG to aurora
ggsave(filename="Figure-05b_2020-10-08_FAIR-IndividualChecksOverTime_withACADIS.jpg",
       path=here("figures"),
       dpi = 400,
       units="in",
       width=13,
       height=7.3)
```


```{r}
#remove unnecessary stuff
rm(list=setdiff(ls(), c("checks_individual_ADC", "indivChecks_clean_withCalcs", "preADC_series_id", "plot5")))
```


###Figure 6:

```{r}
all_checks_ADC_post2016 <- checks_individual_ADC[which(!(checks_individual_ADC$series_id %in% preADC_series_id$series_id)),]


test.tmp <- all_checks_ADC_post2016 %>%
  mutate(check_status_num = case_when(
    check_status == "SUCCESS" ~ 1,
    check_status == "FAILURE" ~ 0)) %>%
  arrange(series_id, check_level, check_name, date_uploaded, filename) %>%
  group_by(series_id, check_level, check_name) %>%
  filter(check_status=="SUCCESS") %>%
  mutate(days_since_submission= as.numeric(difftime(date_uploaded, min(date_uploaded), units="days")))
```

```{r}
hist(test.tmp$days_since_submission, breaks=100)
```


```{r}
mean(test.tmp$days_since_submission)
median(test.tmp$days_since_submission)

test.tmp2 <- test.tmp %>%
  group_by(series_id) %>%
  summarize(submission_length_max = max(days_since_submission),
            n=n()/51)

mean(test.tmp2$submission_length_max)
median(test.tmp2$submission_length_max)

mean(test.tmp2$n)
median(test.tmp2$n)

quantile(test.tmp2$submission_length_max, .95)
```


```{r}
#find the days_since_submission where each check for each series_id becomes a 1

```








